# Python

GOLANG_MAIN_VERSION = go1.26
GOLANGT_TAG = go1.26.5
GOLANG_VERSOIN = 1.26.5-1~bpo13+1
GOLANG_VERSOIN_FIPS = $(GOLANG_VERSOIN)+fips
GOLANG = golang-$(GOLANG_MAIN_VERSION)_$(GOLANG_VERSOIN_FIPS)_all.deb
$(GOLANG)_SRC_PATH = $(SRC_PATH)/golang
$(GOLANG)_MAKEFILE = Makefile
$(GOLANG)_DEPENDS = $(SYMCRYPT_OPENSSL)

MAIN_TARGETS += $(GOLANG)
$(GOLANG)_DERIVED_DEBS = golang-$(GOLANG_MAIN_VERSION)-src_$(GOLANG_VERSOIN_FIPS)_$(ARCH).deb
$(GOLANG)_DERIVED_DEBS += golang-$(GOLANG_MAIN_VERSION)-go_$(GOLANG_VERSOIN_FIPS)_$(ARCH).deb
$(GOLANG)_DERIVED_DEBS += golang-$(GOLANG_MAIN_VERSION)-doc_$(GOLANG_VERSOIN_FIPS)_all.deb
